version: 2.1

orbs:
  doctl: digitalocean/cli@0.1.1

jobs:
  test_if_it_works:
    executor: doctl/default
    steps:
      - doctl/install
      - doctl/initialize
      - add_ssh_keys:
          fingerprints:
            - 68:ef:da:28:80:25:4f:ac:86:d2:5d:7d:c0:ac:52:94
      - run:
          name: Get droplet info
          command: |
            doctl compute ssh $DIGITALOCEAN_DROPLET_ID --ssh-command='./hello.sh' --ssh-user=circleci

workflows:
  test_workflow:
    jobs:
      - test_if_it_works:
          context: digitalocean-deploy-test
