version: 2.1

orbs:
  doctl: digitalocean/cli@0.1.1

jobs:
  test_if_it_works:
    executor: doctl/default
    steps:
      - doctl/install
      - doctl/initialize
      - add_ssh_keys:
          fingerprints:
            - 9b:84:62:0b:92:85:1c:26:8d:fa:c4:d0:a3:3d:1c:b9
      - run:
          name: Get droplet info
          command: |
            doctl compute ssh $DIGITALOCEAN_DROPLET_ID --ssh-command './hello.sh'

workflows:
  test_workflow:
    jobs:
      - test_if_it_works:
          context: digitalocean-deploy-test
