version: 2.1

orbs:
  doctl: digitalocean/cli@0.1.1

jobs:
  test_if_it_works:
    docker:
      - image: alpine
    steps:
      - run:
          name: Testing doctl...
          command: |
            doctl account get

workflows:
  test_workflow:
    jobs:
      - doctl/install_and_initialize_cli:
          context: digitalocean-deploy-test
          executor: doctl/default
      - test_if_it_works:
          requires:
            - doctl/install_and_initialize_cli