version: 2.1

orbs:
  doctl: digitalocean/cli@0.1.1

jobs:
  test_if_it_works:
    executor: doctl/default
    steps:
      - doctl/install
      - doctl/initialize
      - run:
          name: Testing doctl...
          command: |
            doctl account get

workflows:
  test_workflow:
    jobs:
      - test_if_it_works:
          context: digitalocean-deploy-test
