version: 2.1

orbs:
  doctl: digitalocean/cli@0.1.1

jobs:
  test_if_it_works:
    executor: doctl/default
    steps:
      - doctl/install
      - doctl/initialize
      - add_ssh_keys:
          fingerprints:
            - 38:f6:8d:8f:ab:53:28:a6:d6:66:60:2d:6f:6f:48:5b
      - run:
          name: Get droplet info
          command: |
            doctl compute ssh $DIGITALOCEAN_DROPLET_ID --ssh-command './hello.sh'

workflows:
  test_workflow:
    jobs:
      - test_if_it_works:
          context: digitalocean-deploy-test
