version: 2.1

orbs:
  doctl: digitalocean/cli@0.1.1

jobs:
  test_if_it_works:
    executor: doctl/default
    steps:
      - doctl/install
      - doctl/initialize
      - run:
          name: Get droplet info
          command: |
            ls -larth /root/.ssh
          # command: |
            # doctl compute ssh $DIGITALOCEAN_DROPLET_ID --ssh-command='./hello.sh' --ssh-user=circleci

workflows:
  test_workflow:
    jobs:
      - test_if_it_works:
          context: digitalocean-deploy-test
