version: 2.1

orbs:
  doctl: digitalocean/cli@0.1.1

jobs:
  test_if_it_works:
    executor: doctl/default
    steps:
      - doctl/install
      - doctl/initialize
      - add_ssh_keys:
          fingerprints:
            - "68:ef:da:28:80:25:4f:ac:86:d2:5d:7d:c0:ac:52:94"
      - checkout
      - run:
          name: Scan droplet SSH key to avoid prompt
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H $(doctl compute droplet get $DIGITALOCEAN_DROPLET_ID --format PublicIPv4 --no-header) >> ~/.ssh/known_hosts
      - run:
          name: SSH into droplet and execute deploy script
          command: doctl compute ssh $DIGITALOCEAN_DROPLET_ID --ssh-command='bash -s' < ./deploy.sh

workflows:
  test_workflow:
    jobs:
      - test_if_it_works:
          context: digitalocean-deploy-test
