version: 2.1

orbs:
  doctl: digitalocean/cli@0.1.1

jobs:
  test_if_it_works:
    executor: doctl/default
    steps:
      - doctl/install
      - doctl/initialize
      - run:
          name: Create id_rsa file with private ssh key
          command: |
            mkdir ~/.ssh
            ssh-keyscan -H $(doctl compute droplet get $DIGITALOCEAN_DROPLET_ID --format PublicIPv4 --no-header) >> ~/.ssh/known_hosts
            echo $ID_RSA | base64 -d > ~/.ssh/id_rsa
            chmod 400 ~/.ssh/id_rsa
      - run:
          name: SSH into droplet and execute deploy script
          command: doctl compute ssh $DIGITALOCEAN_DROPLET_ID --ssh-user root --ssh-key-path ~/.ssh/id_rsa --ssh-command='./hello.sh'

workflows:
  test_workflow:
    jobs:
      - test_if_it_works:
          context: digitalocean-deploy-test
