version: 2.1

orbs:
  doctl: digitalocean/cli@0.1.1

jobs:
  test_if_it_works:
    executor: doctl/default
    steps:
      - doctl/install
      - doctl/initialize
      - run:
          name: Create id_rsa file with public ssh key
          command: echo $ID_RSA | base64 -d > id_rsa && chmod 400 id_rsa
      - run:
          name: SSH into droplet and execute deploy script
          command: doctl compute ssh $DIGITALOCEAN_DROPLET_ID --ssh-user root --ssh-key-path id_rsa --ssh-command='./hello.sh'

workflows:
  test_workflow:
    jobs:
      - test_if_it_works:
          context: digitalocean-deploy-test
